### ISSUE TITLE
Theme switching

### ISSUE THREAD

**Issue by Brocman** [ibillingsley/HumbleNewTabPage#93]
Please implement automatic theme switching when night mode macOS.

**Comment by dee-me-tree-or-love** [comment]
This is a nice idea, I had the same feeling as @Brocman. @ibillingsley, I'm not sure I will get the time for this, but I might give it a try in the coming time. Are you currently accepting PRs?

**Comment by ibillingsley** [comment]
I'm not currently accepting PRs because I am planning a rewrite for manifest V3 once it becomes mandatory.

It would be simple enough to change the default theme based on light/dark mode, but to properly support switching we would need to save 2 separate theme configs, since they are customizable.

Also requested in #103

**Comment by astrocaat** [comment]
hey @ibillingsley, do you have any updates on this now that you took care of manifest V3?

**Comment by dee-me-tree-or-love** [comment]
@ibillingsley @astrocaat @Brocman, I've started making a fork and got some basic version running, I'll open a draft PR soon and hope to return to it sometime next week as I find the time :) Hope that's still interesting? 

_Here's the first impression:_
![2023-11-24 11 54 53](https://github.com/ibillingsley/HumbleNewTabPage/assets/12134172/28a7e563-150b-4bd8-a786-0847641c46bf)

Suggestions and improvements are of course welcome, I'll ping you in the draft PR soon too. 
:v:

**Comment by patrickhuijten** [comment]
At the request of @dee-me-tree-or-love ❤ 

For those interested in a workaround, I found that adding a small CSS snippet to the advanced CSS panel can at least save our eyes from being blinded at night when using a bright theme.

![Image](https://github.com/user-attachments/assets/e8f3d45f-d85a-407e-8ac3-f04813b19b10)

**Snippet**
```css
body {
  --bg-dark: rgb(21, 27, 35);
  --text-dark: rgb(165 175 186);

  transition: background-color 100ms ease;
}
@media (prefers-color-scheme: dark) {
  #main a {
    color: var(--text-dark);
  }
  body {
    background-color: var(--bg-dark);
  }
}
```

**CSS variable tweaking**
The snippet uses CSS variable, so you can tweak the specific CSS property in dev tools and then go ahead and store that in the CSS variable section of the snippet 😄 
![Image](https://github.com/user-attachments/assets/56daa368-a17e-42ed-8fbf-bcd0732dab79)
